-- 0001_zones.sql  (GENERATED by db/generate-placeholder-zones.mjs — do not hand-edit)
-- BLOCKER-1: PLACEHOLDER polygons (is_placeholder = true). Not real ward
-- boundaries. Replace with authoritative GCC/CCMC GeoJSON before launch.
-- Tamil names are best-effort; verify with a native reader (HARD RULE 4).

INSERT INTO municipal_zones (city, zone_name, zone_name_ta, is_placeholder, geom)
VALUES
  ('Chennai', 'Zone 1 - Thiruvottiyur', 'மண்டலம் 1 - திருவொற்றியூர்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.150000, 12.850000, 80.190000, 12.983333), 4326))),
  ('Chennai', 'Zone 2 - Manali', 'மண்டலம் 2 - மணலி', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.190000, 12.850000, 80.230000, 12.983333), 4326))),
  ('Chennai', 'Zone 3 - Madhavaram', 'மண்டலம் 3 - மாதவரம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.230000, 12.850000, 80.270000, 12.983333), 4326))),
  ('Chennai', 'Zone 4 - Tondiarpet', 'மண்டலம் 4 - தண்டையார்பேட்டை', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.270000, 12.850000, 80.310000, 12.983333), 4326))),
  ('Chennai', 'Zone 5 - Royapuram', 'மண்டலம் 5 - ராயபுரம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.310000, 12.850000, 80.350000, 12.983333), 4326))),
  ('Chennai', 'Zone 6 - Thiru-Vi-Ka Nagar', 'மண்டலம் 6 - திரு-வி-க நகர்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.150000, 12.983333, 80.190000, 13.116667), 4326))),
  ('Chennai', 'Zone 7 - Ambattur', 'மண்டலம் 7 - அம்பத்தூர்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.190000, 12.983333, 80.230000, 13.116667), 4326))),
  ('Chennai', 'Zone 8 - Anna Nagar', 'மண்டலம் 8 - அண்ணா நகர்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.230000, 12.983333, 80.270000, 13.116667), 4326))),
  ('Chennai', 'Zone 9 - Teynampet', 'மண்டலம் 9 - தேனாம்பேட்டை', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.270000, 12.983333, 80.310000, 13.116667), 4326))),
  ('Chennai', 'Zone 10 - Kodambakkam', 'மண்டலம் 10 - கோடம்பாக்கம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.310000, 12.983333, 80.350000, 13.116667), 4326))),
  ('Chennai', 'Zone 11 - Valasaravakkam', 'மண்டலம் 11 - வளசரவாக்கம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.150000, 13.116667, 80.190000, 13.250000), 4326))),
  ('Chennai', 'Zone 12 - Alandur', 'மண்டலம் 12 - ஆலந்தூர்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.190000, 13.116667, 80.230000, 13.250000), 4326))),
  ('Chennai', 'Zone 13 - Adyar', 'மண்டலம் 13 - அடையார்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.230000, 13.116667, 80.270000, 13.250000), 4326))),
  ('Chennai', 'Zone 14 - Perungudi', 'மண்டலம் 14 - பெருங்குடி', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.270000, 13.116667, 80.310000, 13.250000), 4326))),
  ('Chennai', 'Zone 15 - Sholinganallur', 'மண்டலம் 15 - சோளிங்கநல்லூர்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(80.310000, 13.116667, 80.350000, 13.250000), 4326))),
  ('Coimbatore', 'East Zone', 'கிழக்கு மண்டலம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(76.900000, 10.950000, 76.930000, 11.100000), 4326))),
  ('Coimbatore', 'West Zone', 'மேற்கு மண்டலம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(76.930000, 10.950000, 76.960000, 11.100000), 4326))),
  ('Coimbatore', 'North Zone', 'வடக்கு மண்டலம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(76.960000, 10.950000, 76.990000, 11.100000), 4326))),
  ('Coimbatore', 'South Zone', 'தெற்கு மண்டலம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(76.990000, 10.950000, 77.020000, 11.100000), 4326))),
  ('Coimbatore', 'Central Zone', 'மத்திய மண்டலம்', true, ST_Multi(ST_SetSRID(ST_MakeEnvelope(77.020000, 10.950000, 77.050000, 11.100000), 4326)))
ON CONFLICT (city, zone_name) DO NOTHING;
